interface User {
  id: string;
  name: string | null;
  email: string;
}

interface Message {
  id: string;
  role: 'user' | 'assistant' | 'system';
  content: string;
  stage: string;
  createdAt: Date;
}

interface Perspective {
  id: string;
  userId: string;
  observation: string | null;
  feeling: string | null;
  need: string | null;
  request: string | null;
  user: User;
}

interface Agreement {
  id: string;
  content: string;
  agreedByUser1: boolean;
  agreedByUser2: boolean;
  createdAt: Date;
}

interface SessionExportData {
  id: string;
  topic: string;
  stage: string;
  status: string;
  createdAt: Date;
  updatedAt: Date;
  initiator: User;
  partnership?: {
    user1: User;
    user2: User | null;
  } | null;
  messages: Message[];
  perspectives: Perspective[];
  agreements: Agreement[];
}

function formatDate(date: Date): string {
  return new Date(date).toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });
}

function formatDateTime(date: Date): string {
  return new Date(date).toLocaleString('en-US', {
    year: 'numeric',
    month: 'short',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  });
}

function formatStage(stage: string): string {
  return stage
    .split('_')
    .map(word => word.charAt(0).toUpperCase() + word.slice(1))
    .join(' ');
}

function getUserName(user: User | null | undefined): string {
  if (!user) return 'Unknown';
  return user.name || user.email.split('@')[0];
}

function getRoleLabel(role: string): string {
  switch (role) {
    case 'user':
      return 'You';
    case 'assistant':
      return 'AI Mediator';
    case 'system':
      return 'System';
    default:
      return role;
  }
}

export function generateSessionMarkdown(session: SessionExportData): string {
  const lines: string[] = [];

  // Header
  lines.push('# Session Summary');
  lines.push('');
  lines.push(`**Topic:** ${session.topic}`);
  lines.push('');
  lines.push('---');
  lines.push('');

  // Metadata
  lines.push('## Session Details');
  lines.push('');
  lines.push(`| Field | Value |`);
  lines.push(`|-------|-------|`);
  lines.push(`| Started | ${formatDate(session.createdAt)} |`);
  lines.push(`| Last Updated | ${formatDate(session.updatedAt)} |`);
  lines.push(`| Status | ${session.status.charAt(0).toUpperCase() + session.status.slice(1)} |`);
  lines.push(`| Current Stage | ${formatStage(session.stage)} |`);
  lines.push(`| Initiated By | ${getUserName(session.initiator)} |`);
  if (session.partnership?.user2) {
    lines.push(`| Partner | ${getUserName(session.partnership.user2)} |`);
  }
  lines.push('');

  // NVC Perspectives
  if (session.perspectives.length > 0) {
    lines.push('---');
    lines.push('');
    lines.push('## NVC Perspectives');
    lines.push('');

    for (const perspective of session.perspectives) {
      lines.push(`### ${getUserName(perspective.user)}'s Perspective`);
      lines.push('');

      if (perspective.observation) {
        lines.push(`**Observation:** ${perspective.observation}`);
        lines.push('');
      }
      if (perspective.feeling) {
        lines.push(`**Feeling:** ${perspective.feeling}`);
        lines.push('');
      }
      if (perspective.need) {
        lines.push(`**Need:** ${perspective.need}`);
        lines.push('');
      }
      if (perspective.request) {
        lines.push(`**Request:** ${perspective.request}`);
        lines.push('');
      }
    }
  }

  // Agreements
  if (session.agreements.length > 0) {
    lines.push('---');
    lines.push('');
    lines.push('## Agreements Reached');
    lines.push('');

    for (const agreement of session.agreements) {
      lines.push(`> ${agreement.content}`);
      lines.push('');
      const agreedBy: string[] = [];
      if (agreement.agreedByUser1) agreedBy.push('User 1');
      if (agreement.agreedByUser2) agreedBy.push('User 2');
      lines.push(`*Agreed by: ${agreedBy.length > 0 ? agreedBy.join(' & ') : 'Pending'}*`);
      lines.push('');
    }
  }

  // Conversation Transcript
  lines.push('---');
  lines.push('');
  lines.push('## Conversation Transcript');
  lines.push('');

  if (session.messages.length === 0) {
    lines.push('*No messages in this session.*');
    lines.push('');
  } else {
    for (const message of session.messages) {
      const roleLabel = getRoleLabel(message.role);
      const timestamp = formatDateTime(message.createdAt);

      lines.push(`### ${roleLabel}`);
      lines.push(`*${timestamp}*`);
      lines.push('');
      lines.push(message.content);
      lines.push('');
    }
  }

  // Footer
  lines.push('---');
  lines.push('');
  lines.push(`*Generated by Talk It Out AI on ${formatDate(new Date())}*`);

  return lines.join('\n');
}
